resources:
- name: credential-service-api
  type: git
  source:
    uri: https://github.com/dellemc-symphony/credential-service-api.git
    branch: concourse

- name: servers
  type: git
  source:
    uri: https://github.com/chamap1/shared-libraries.git
    branch: master

jobs:
- name: package
  public: true
  plan:
  - get: credential-service-api
    trigger: true
  - task: compile
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}

      inputs:
      - name: credential-service-api

      run:
        path: bash
        dir: credential-service-api/
        args:
        - -exc
        - |
          echo compile
 
- name: push-to-artifactory
  public: true
  plan:
  - get: credential-service-api
    passed: [package]
    trigger: true
  - get: servers
    trigger: true
  - task: deploy
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}

      inputs:
      - name: credential-service-api
      - name: servers

      run:
        path: bash
        dir: credential-service-api/
        args:
        - -exc
        - |
          cp ../servers/settings.xml . 
          echo deploy  
           
- name: bosh-deploy
  public: true
  plan:
  - get: credential-service-api
    passed: [push-to-artifactory]
    trigger: true
  - task: deploy
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: bosh/bosh-lite}

      inputs:
      - name: credential-service-api

      run:
        path: /usr/bin/start-bosh
        args:
        - -exc
        - |
          echo boshdeploy  
